<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Pranav-Yadav" failures="1" tests="2" name="Default test(failed)(failed)" time="0.056" errors="0" timestamp="2022-05-28T16:35:34 IST">
  <testcase classname="TestNgRetryFailedTest.TestNgRetryFailedTestDemo" name="test2" time="0.01"/>
  <testcase classname="TestNgRetryFailedTest.TestNgRetryFailedTestDemo" name="test3" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestNgRetryFailedTest.TestNgRetryFailedTestDemo.test3(TestNgRetryFailedTestDemo.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="TestNgRetryFailedTest.TestNgRetryFailedTestDemo" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed)(failed) -->
